# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-16 13:53
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_by_company', models.CharField(blank=True, choices=[('rejected', 'Rejected'), ('shortlisted', 'Shortlisted'), ('waiting', 'Put on Hold')], max_length=20, null=True)),
                ('is_shortlisted', models.NullBooleanField()),
                ('is_rejected', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='job_title', unique=True)),
                ('job_type', models.CharField(blank=True, choices=[('fulltime', 'Full Time'), ('contract', 'Contract'), ('intern', 'Intern'), ('freelance', 'Freelance'), ('parttime', 'Part Time')], help_text='<strong>Select Type of job </strong>', max_length=10, null=True)),
                ('job_desc', models.TextField()),
                ('job_min_ctc', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], null=True)),
                ('job_max_ctc', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], null=True)),
                ('job_min_exp', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)])),
                ('job_max_exp', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)])),
                ('job_location', models.CharField(blank=True, max_length=100, null=True)),
                ('job_skills', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('job_no_of_applications', models.IntegerField(blank=True, default=0)),
                ('company', models.ForeignKey(help_text='<strong>Select Company from dropdown', null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'ordering': ['-job_min_ctc'],
            },
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.JobListing'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='jobseeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile'),
        ),
    ]
